spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

broker:
  kis:
    base-url: https://openapi.koreainvestment.com:9443
